// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackBackground: typeof import('./components/gallery/cardBack/BackBackground.vue')['default']
    BackCard: typeof import('./components/gallery/cardBack/BackCard.vue')['default']
    BackCloseButton: typeof import('./components/gallery/cardBack/BackCloseButton.vue')['default']
    BackDesc: typeof import('./components/gallery/cardBack/BackDesc.vue')['default']
    Background: typeof import('./components/Background.vue')['default']
    BackIngredientsList: typeof import('./components/gallery/cardBack/BackIngredientsList.vue')['default']
    BackNotes: typeof import('./components/gallery/cardBack/BackNotes.vue')['default']
    BackSteps: typeof import('./components/gallery/cardBack/BackSteps.vue')['default']
    BackTitle: typeof import('./components/gallery/cardBack/BackTitle.vue')['default']
    DarkBackground: typeof import('./components/gallery/cardBack/DarkBackground.vue')['default']
    DarkThemeButton: typeof import('./components/DarkThemeButton.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FrontCard: typeof import('./components/gallery/cardFront/FrontCard.vue')['default']
    FrontTitle: typeof import('./components/gallery/cardFront/FrontTitle.vue')['default']
    Gallery: typeof import('./components/gallery/Gallery.vue')['default']
    GalleryCard: typeof import('./components/gallery/GalleryCard.vue')['default']
    GalleryCardBack: typeof import('./components/gallery/cardBack/GalleryCardBack.vue')['default']
    GalleryCardFront: typeof import('./components/gallery/cardFront/GalleryCardFront.vue')['default']
    GalleryGrid: typeof import('./components/gallery/GalleryGrid.vue')['default']
    ScrollButton: typeof import('./components/scrolling/ScrollButton.vue')['default']
    ScrollToEdge: typeof import('./components/scrolling/ScrollToEdge.vue')['default']
    SearchBar: typeof import('./components/gallery/searchBar/SearchBar.vue')['default']
    SearchInput: typeof import('./components/gallery/searchBar/SearchInput.vue')['default']
  }
}
